-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjo7OlG7ZZIG+OCi6
FPgK1jP1zsyI/h0KeaPbSvjGTGegCgYIKoZIzj0DAQehRANCAAT9tvZoQjkgQyA2
00pSgxVDiJSneD+o0/jVJBEb9bqFjVPWnuPrGH0E6IFT0vvH6vhMrXg8KM/gm8CL
WUVBgQLt
-----END PRIVATE KEY-----